controllers/user_controller.py
from flask import Blueprint, request, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required
from models.user_model import User
from views import user_view
from database import db

user_bp = Blueprint('user',__name__,url_prefix="/")



@user_bp.route("/")
def index():
    return user_view.login()



#Funcion registrar usuario 
@user_bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        name = request.form['name']
        email = request.form['email']
        username = request.form['username']
        password = request.form['password']

        if User.get_by_username(username):
            flash('El nombre de usuario ya existe.', 'danger')
        else:
            new_user = User(name, email, username, password)
            db.session.add(new_user)
            db.session.commit()
            flash('Usuario registrado correctamente. Inicia sesión.', 'success')
            return redirect(url_for('user.login'))

    return user_view.register()


#Funcion logear
@user_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        user = User.get_by_username(username)

        if user and user.verify_password(password):
            login_user(user)
        
            #¡flash('Inicio de sesión exitoso', 'success')
            return redirect(url_for('vehiculo.index'))
        else:
            flash('Credenciales inválidas', 'danger')

    return user_view.login()




#Funcion cerrar session
@user_bp.route('/dashboard')
@login_required
def dashboard():
    return user_view.dashboard()

@user_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Has cerrado sesión', 'info')
    return redirect(url_for('user.login'))

views/user_view.py
from flask import render_template
from flask_login import current_user

"""def index():
    return render_template("user/index.html")
"""
def login():
    return render_template("user/login.html")

def register():
    return render_template("user/register.html")

def dashboard(user):
    return render_template('usuarios/index.html', user=user)

templates/user/dashboard.html
{% extends 'base2.html'%}
{%block title%} Panel de Usuario{%endblock%}
{%block content%}
<div class="container mt-4">
    <h2 class="mb-4">Bienvenido,{{ name }}!</h2>
    <div class="card">
        <div class="card-body">
            <p><strong>Nombre de usuario:</strong>{{current_user.username}}</p>
            <p><strong>Correo electronico:</strong>{{ current_user.email}}</p>
          
            <div class="text-center mt-4">
                <a style="background-color: red;"  href="{{ url_for('user.logout') }}" class="btn btn-primary">Cerrar Sesión</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/user/index.html
{% extends 'base2.html' %}
{% block title %}Inicio{% endblock %}

{% block content %}
<h1>Bienvenido a la App</h1>
<h1>Ventas</h1>
{% if current_user.is_authenticated %}


    <p>Hola, {{ current_user.username }}. Ya iniciaste sesión.</p>
    <a href="{{ url_for('user.logout') }}" class="btn btn-danger">Cerrar Sesión</a>
    <a href="{{ url_for('usuario.index') }}" class="btn btn-info">Ir al Panel</a>
{% else %}
    <a href="{{ url_for('user.register') }}" class="btn btn-primary">Registrarse</a>
    <a href="{{ url_for('user.login') }}" class="btn btn-success">Iniciar Sesión</a>
{% endif %}

{% endblock %}

templates/user/login.html
{% extends 'base2.html'%}
{% block title %}Login{% endblock %}
{% block content %}
<link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">

<div class="container my-5">
    <div class="text-center mb-4">
        <h1 class="titulo1">Gestion de Activos Fijos</h1>
        <h2>Optimiza y Controla el Valor de tus Bienes</h2>
        <h3 class="mt-4 ">Iniciar Sesión</h3>
    </div>

    <div class="d-flex justify-content-center">
        <form action="{{ url_for('user.login') }}" method="POST" class="w-100" style="max-width: 500px;">


            <div class="mb-3">
                <label for="username" class="form-label">Usuario:</label>
                <input type="text" name="username" class="form-control" required>
            </div>

            <div class="mb-3">
                <label for="password" class="form-label">Contraseña:</label>
                <input type="password" name="password" class="form-control" required>
            </div>

            <div class="mb-3 text-start">
                <button class="submit1">Iniciar Sesión</button>
            </div>

            <div class="d-flex justify-content-between mt-3">
                <a href="{{ url_for('user.register') }}" style="color: white;" class="text-decoration-none">
                    ¿Aún no tienes una cuenta? Regístrate aquí
                </a>
                <a href="#" class="text-decoration-none" style="color: white;">
                    ¿Olvidaste tu Contraseña?
                </a>
            </div>
        </form>
    </div>

</div>

{% endblock %}

templates/user/register.html
{% extends 'base2.html' %}
{% block title %}Registro{% endblock %}

{% block content %}
<link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
<div class="container my-5"> <!-- Margen vertical agregado -->

    <div class="text-center mb-4">
        <h1 class="titulo">Gestion de Activos Fijos</h1>
        <h2>Optimiza y Controla el Valor de tus Bienes</h2>
        <h3 class="mt-4 ">Crea tu cuenta para administrar tus activos</h3>
    </div>
 
    <div class="d-flex justify-content-center">
        <form action="{{ url_for('user.register') }}" method="POST" class="w-100" style="max-width: 500px;">
            <div class="mb-3">
                <label for="name" class="form-label ">Nombre:</label>
                <input type="text" name="name" class="form-control " required>
            </div>
            <div class="mb-3">
                <label for="email" class="form-label ">Email:</label>
                <input type="email" name="email" class="form-control " required>
            </div>
            <div class="mb-3">
                <label for="username" class="form-label ">Usuario:</label>
                <input type="text" name="username" class="form-control " required>
            </div>
          
            <div class="mb-3">
                <label for="password" class="form-label ">Contraseña:</label>
                <input type="password" name="password" class="form-control " required>
            </div>
            
            <div class="mb-3 text-start">
                <button class="submit">Crear Cuenta</button>
            </div>
             <div class="d-flex justify-content-between mt-3">
                <a href="{{ url_for('user.login') }}"class="d-block text-decoration-none" style="color: white;"  >¿Ya tienes cuenta? Iniciar Sesión</a>
                <a href="#"class="d-block text-decoration-none" style="color: white;" >¿Olvidaste tu Contraseña?</a>
            </div>
        </form>
    </div>

</div>
{% endblock %}